name: Pre Merge Checks

on:
  workflow_dispatch:
  merge_group:
  pull_request:

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  gradle-validation:
    name: Gradle validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # v6

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5
        with:
          java-version-file: .github/.java-version
          distribution: 'zulu'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # v6

      - name: Assemble all variants
        run: ./gradlew app:assemble --continue

  jvm-tests:
    name: Run local tests for all projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5
        with:
          java-version-file: .github/.java-version
          distribution: 'zulu'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # v6

      - name: Run local tests
        run: ./gradlew test --continue --stacktrace
